### ISSUE TITLE
Switch to standard notation for `general_parallel`

### ISSUE THREAD

**Issue by jeltsch** [input-output-hk/thorn-calculus#102]
For now, we have been using `∏` for `general_parallel`. This is non-standard however. Furthermore, it clashes with the use of `∏` for multi-arity group products. We have tried to solve the latter issue by removing the group-related notation in `Thorn_Calculus-Processes`. However, it gets reintroduced in `Thorn_Calculus-Semantics-Synchronous`, apparently by importing theories from `Transition_Systems`, which don’t have this notation removed. While the ambiguities this causes in theories other than `Thorn_Calculus-Processes` can all be resolved by type checking, having these ambiguities in the first place is still not good.

We shall solve these problems by switching from `∏` to `‖` (`\<Parallel>`). The use of a “big” version of the ordinary parallel composition operator seems to be sufficiently standard; at least. it Milner uses it in a paper on CCS.

**Comment by javierdiaz72** [comment]
A further note: Actually, big `‖` is quite common in the literature related to ACP, since `‖` is used for parallel composition (as is the case for CSP as well), unlike the cases of CCS and the π-calculus in which `|` is used instead, and therefore `∏` is common use (I guess using a big `|` would be a bit awkward).
